WebApp/Controllers/ChristmasController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.ChristmasFactory.Web.Controllers
{
    public class ChristmasController : Controller
    {
        public IActionResult Welcome()
        {
            return View();
        }

        public IActionResult Contact()
        {
            //Si ma requete est en get, je charge ma vue par défaut
            if (Request.Method == "GET")
            {
            return View();
            }
            //sinon j'affiche un message
            else
            {
                //Récupérer les données postéesS
                string email = Request.Form["email"];
                string message = Request.Form["message"];
                String[] args = new String[] { email, message};

                return View(args);
            }
        }

        //public IActionResult ExempleQS()
        //{
        //    // /christmas/exempleqs?word=hello&lang=fr*

        //    //Récupérer les paramètres
        //    string word = Request.Query["word"];
        //    string lang = Request.Query["lang"];
        //    int nb = int.Parse(Request.Query["nb"]);

        //    string traduction = "";

        //    for (int i = 0; i < nb; i++)
        //    {
        //        traduction += word + "<br/>";
        //    }
        //    Response.ContentType = "text/html";
        //    return Content(traduction);
        //}
    }
}

WebApp/Controllers/ElfController.cs
using Microsoft.AspNetCore.Mvc;
using Fr.EQL.AI110.ChristmasFactory.Business;
using Fr.EQL.AI110.ChristmasFactory.Entities;
using Fr.EQL.AI110.ChristmasFactory.Web.Models;

namespace Fr.EQL.AI110.ChristmasFactory.Web.Controllers
{
    public class ElfController : Controller
    {
        private IActionResult EditerElfe(string rubrique, Elf elf)
        {
            ViewBag.Rubrique = rubrique;
            return View("Edit", elf);
        }

        //par défaut : GET
        //attribut httpGet
        [HttpGet]
        public IActionResult Create()
        {
            ElfBusiness bu = new ElfBusiness();
            ElfCategoryBusiness elfCatBu = new ElfCategoryBusiness();
            ViewBag.Categories = elfCatBu.GetElfCategories();
            return EditerElfe("Création d'un elfe", null);

        }
        [HttpPost]
        public IActionResult Create(Elf elf)
        {
            ElfCategoryBusiness elfCatBu = new ElfCategoryBusiness();
            ViewBag.Categories = elfCatBu.GetElfCategories();

            if (ModelState.IsValid)
            {
                ElfBusiness bu = new ElfBusiness();
                if (elf.IdCategory == 0 )
                {
                    elf.IdCategory = 1;
                }
                bu.SaveElf(elf);
                return RedirectToAction("Index");
            }
            else
            {
                return EditerElfe("Création d'un elfe", elf);
            }

        }
        [HttpGet]
        public IActionResult Index()
        {
            ElfSearchViewModel model = new ElfSearchViewModel();

            ElfBusiness elfBu = new ElfBusiness();
            ElfCategoryBusiness elfCatBu = new ElfCategoryBusiness();
            model.Elves = elfBu.SearchElves("",null,"",0);
            model.CategoryNames = elfCatBu.GetElfCategories();
            return View(model);

            //try
            //{
            //ElfBusiness bu = new ElfBusiness();
            //List<Elf> elves = bu.GetElves();
            //return View(elves);
            //}
            //catch (Exception ex)
            //{
            //    ViewBag.Error = ex.Message;
            //    return View("Error");
            //}
            
        }
        [HttpPost]
        public IActionResult Index(ElfSearchViewModel model)
        {
            ElfBusiness elfBu = new ElfBusiness();
            model.Elves = elfBu.SearchElves(model.ElfName,model.IsAvailable,model.ElfPicture,model.IdCategory);
            ElfCategoryBusiness elfCatBu = new ElfCategoryBusiness();
            model.CategoryNames = elfCatBu.GetElfCategories();
            return View(model);
            
        }

        public IActionResult Infos(int id)
        {
            ElfBusiness bu = new ElfBusiness();
            Elf elf = bu.GetElfById(id);
            return View("Detail",elf);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ElfBusiness bu = new ElfBusiness();
            Elf elf = bu.GetElfById(id);
            ElfCategoryBusiness elfCatBu = new ElfCategoryBusiness();
            ViewBag.Categories = elfCatBu.GetElfCategories();
            return EditerElfe("Modification d'un elfe", elf);
        }
        [HttpPost]
        public IActionResult Update(Elf elf)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ElfBusiness bu = new ElfBusiness();
                    bu.SaveElf(elf);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return EditerElfe("Modification d'un elfe", elf);
                }
            }
            else
            {
                return EditerElfe("Modification d'un elfe", elf);
            }

        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                id = int.Parse(Request.Form["idsupp"]);
            }
            try
            {
                ElfBusiness bu = new ElfBusiness();
                bu.DeleteElf(id);
            }
            catch (Exception ex)
            {
                TempData.Add("Erreur", "Votre elfe ne peut être supprimé car il est en pleine fabrication de jouet!");
                return RedirectToAction("Index");
            }
            return View("Index");
        }

        #region QueryString
        public IActionResult Detail()
        {
            int id = int.Parse(Request.Query["id"]);
            ElfBusiness bu = new ElfBusiness();
            Elf elf = bu.GetElfById(id);
            return View(elf);
        }
        #endregion

        #region Create
        //ancienne version
        public IActionResult Nouveau()
        {
            if (Request.Method == "GET")
            {
                return View();
            }
            else
            {
                bool isAvailable = false;
                string name = Request.Form["name"];
                string img = Request.Form["img"];
                if (Request.Form["checkbox"] != "")
                {
                    isAvailable = true;
                }
                ElfBusiness bu = new ElfBusiness();
                Elf elf = new Elf(0,name,isAvailable,img);
                bu.SaveElf(elf);
                Response.ContentType = "text/html;charset=utf-8";
                return Content("Merci :)");
            }
        }
        #endregion
    }
}

WebApp/Controllers/ToyController.cs
using Fr.EQL.AI110.ChristmasFactory.Business;
using Fr.EQL.AI110.ChristmasFactory.Entities;
using Fr.EQL.AI110.ChristmasFactory.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fr.EQL.AI110.ChristmasFactory.Web.Controllers
{
    public class ToyController : Controller
    {
        private void ElfBu()
        {
            ElfBusiness bu = new ElfBusiness();
            ViewBag.ElfList = bu.GetElves();
        }
        public void ElfName(int id)
        {
            ElfBusiness bu = new ElfBusiness();
            ViewBag.ElfName = bu.GetElfById(id).Name;
        }
        private IActionResult EditToy(string rubrique, Toy toy)
        {
            ViewBag.Rubrique = rubrique;
            return View("Edit", toy);
        }

        [HttpGet]
        public IActionResult Index()
        {
            ToySearchViewModel model = new ToySearchViewModel();

            ToyBusiness toyBu = new ToyBusiness();
            model.Toys = toyBu.SearchToys(0,"",0,0);
            
            ElfBusiness elfBu = new ElfBusiness();
            model.Elves = elfBu.GetElves();

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(ToySearchViewModel model)
        {
           
            ToyBusiness toyBu = new ToyBusiness();
            model.Toys = toyBu.SearchToys(model.IdResponsable, model.ToyName, model.MinPrice, model.MaxPrice);

            ElfBusiness elfBu = new ElfBusiness();
            model.Elves = elfBu.GetElves();

            return View(model);

        }
        [HttpGet]
        public IActionResult Create()
        {
            ElfBu();
            return EditToy("Création d'un jouet",null);
        }

        [HttpPost]
        public IActionResult Create(Toy toy)
        {
            ElfBu();
            if (ModelState.IsValid)
            {
                ToyBusiness bu = new ToyBusiness();
                bu.SaveToy(toy);
                return RedirectToAction("Index");
            } 
            else
            {
                return EditToy("Création d'un jouet", null);
            }
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            ElfBu();
            ToyBusiness bu = new ToyBusiness();
            Toy toy = bu.GetToyById(id);
            return EditToy("Modification d'un jouet", toy);
        }
        [HttpPost]
        public IActionResult Update(Toy toy)
        {
            ElfBu();
            if (ModelState.IsValid)
            {
                try
                {
                ToyBusiness bu = new ToyBusiness();
                bu.SaveToy(toy);
                return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                    return EditToy("Modification d'un jouet", toy);
                }
            }
            else
            {
                return EditToy("Modification d'un jouet", toy);
            }
        }

        public IActionResult Detail(int id)
        {
            ToyBusiness bu = new ToyBusiness();
            Toy toy = bu.GetToyById(id);
            
           if ( toy.IdResponsable != null)
            {
                ElfName((int)toy.IdResponsable);
            }
            return View(toy);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (id ==0)
            {
                id = int.Parse(Request.Form["idsupp"]);
            }
            try
            {
                ToyBusiness bu = new ToyBusiness();
                bu.DeleteToy(id);
            }
            catch
            {
                new Exception("Erreur de suppression");
            }
            return RedirectToAction("Index");
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Christmas" asp-action="Contact">Formulaire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Elf" asp-action="Create">Création d'un elfe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Toy" asp-action="Create">Création d'un jouet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Elf" asp-action="Index">Liste des elfes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Toy" asp-action="Index">Catalogue des Jouets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
            @if (ViewBag.Error != null) {
                 <div class="error-message">@ViewBag.Error</div>
            }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>